config/routes.rb
Rails.application.routes.draw do
  root to: 'map_points#index'
  resources :map_points

  devise_for :users

end

app/models/map_point.rb
class MapPoint < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :map_points
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/map_points_controller.rb
class MapPointsController < ApplicationController
  before_action :set_map_point, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @map_points = MapPoint.all
    respond_with(@map_points)
  end

  def show
    respond_with(@map_point)
  end

  def new
    @map_point = MapPoint.new
    respond_with(@map_point)
  end

  def edit
  end

  def create
    @map_point = MapPoint.new(map_point_params)
    @map_point.user = current_user
    @map_point.save
    redirect_to action: :index
  end

  def update
    @map_point.update(map_point_params)
    respond_with(@map_point)
  end

  def destroy
    @map_point.destroy
    respond_with(@map_point)
  end

  private
    def set_map_point
      @map_point = MapPoint.find(params[:id])
    end

    def map_point_params
      params.require(:map_point).permit(:latitude,:longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_points_helper.rb
module MapPointsHelper
end

app/views/application/_flash.html.erb
<% flash.take(1).each do |key, msg| %>
  <%= content_tag :div, msg, id: key, class: "message" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleMapPoints</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp", 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <% if user_signed_in? %>
        <span> Welcome, <%= current_user.email %></span>
        <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
    </div>
    <div id="main">
      <%= render 'flash' %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/map_points/_form.html.erb
<%= form_for(@map_point) do |f| %>
  <% if @map_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map_point.errors.count, "error") %> prohibited this map_point from being saved:</h2>

      <ul>
      <% @map_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>
  <div>
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/map_points/edit.html.erb
<h1>Editing map_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @map_point %> |
<%= link_to 'Back', map_points_path %>

app/views/map_points/index.html.erb
<h1>Listing map_points</h1>
  <p>Click on the map to add markers.</p>

  <div id="map-canvas"></div>
  
  <div id="panel">
    <input onclick="clearMarkers();" type=button value="Hide Markers">
    <input onclick="showMarkers();" type=button value="Show All Markers">
    <input onclick="deleteMarkers();" type=button value="Delete Markers">
  </div>
  <%= javascript_tag do %>
  window.points = <%=raw @map_points.to_json %>;
  <% end %>
  <table>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
    </tr>
    <% @map_points.each do |map_point| %>
      <tr>
        <td><%= map_point.latitude %></td>
        <td><%= map_point.longitude %></td>
        <td><%= link_to 'Show', map_point %></td>
        <td><%= link_to 'Edit', edit_map_point_path(map_point) %></td>
        <td><%= link_to 'Destroy', map_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<%= link_to 'New Map point', new_map_point_path %>

app/views/map_points/new.html.erb
<h1>New map_point</h1>
<div id="map-canvas"></div>

<%= render 'form' %>

<%= link_to 'Back', map_points_path %>

app/views/map_points/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_map_point_path(@map_point) %> |
<%= link_to 'Back', map_points_path %>